[package]
name = "wikijs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = "0.13"
serde = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
