name: wiki

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: start wiki instance
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
      - name: wait for wiki to be reachable
        uses: cygnetdigital/wait_for_response@v2.0.0
      - name: run initial wiki setup
        run: |
          sudo apt update
          sudo apt install httpie
          scripts/finalize_wiki_setup.sh
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install rust cache
        uses: Swatinem/rust-cache@v2
      - name: run tests
        run: cargo test
