name: wiki

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
      - uses: cygnetdigital/wait_for_response@v2.0.0
      - run: |
          sudo apt update
          sudo apt install httpie
          echo '{
              "adminEmail": "sandro@gierens.de",
              "adminPassword": "password",
              "adminPasswordConfirm": "password",
              "siteUrl": "http://localhost",
              "telemetry": true
          }' | http post http://localhost/finalize
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
